#!/usr/bin/env python3
"""
Stamp out a new WikiReader app from this template.

Reads a topic.json, copies the template to a new folder, renames the Xcode
project (WikiReader -> your app), sets the bundle id, writes a configured
TopicConfig.swift, and applies the accent color. After this, generate the
catalog and build.

    python3 Scripts/scaffold.py topic.json --out ~/Desktop/lost-at-sea

Then:
    cd ~/Desktop/lost-at-sea
    python3 Scripts/generate_catalog.py topic.json
    python3 Scripts/validate_catalog.py
    open <NewApp>.xcodeproj

See topic.example.json for the full schema. Required keys: appName, bundleId,
accentHex, categories. Everything else has sensible defaults.
"""

import argparse
import json
import os
import pathlib
import re
import shutil
import sys

TEMPLATE_NAME = "WikiReader"
TEMPLATE_BUNDLE = "com.example.wikireader"
TEMPLATE_ROOT = pathlib.Path(__file__).resolve().parent.parent
EXCLUDE = {".git", "build", "DerivedData", ".DS_Store"}


def identifier(app_name):
    """'Lost at Sea' -> 'LostAtSea' (a valid Xcode target/identifier)."""
    parts = re.findall(r"[A-Za-z0-9]+", app_name)
    ident = "".join(p[:1].upper() + p[1:] for p in parts)
    return ident or "MyApp"


def swift_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def swift_opt(s):
    return "nil" if s in (None, "") else swift_str(s)


def render_topic_config(t):
    cats = []
    for c in t["categories"]:
        wiki = swift_opt(c.get("wikipediaCategory"))
        cats.append(
            f'        TopicCategory(id: {swift_str(c["id"])}, title: {swift_str(c["title"])}, '
            f'symbol: {swift_str(c.get("symbol", "circle"))}, wikipediaCategory: {wiki}),'
        )
    cats_block = "\n".join(cats)
    thresholds = ", ".join(str(int(x)) for x in t.get("metricThresholds", [1, 5, 10, 20, 50]))
    return f'''import SwiftUI

// ============================================================================
//  TOPIC CONFIG — generated by scaffold.py from topic.json. Safe to hand-edit.
//  Everything topic-specific lives here; the engine reads from it.
// ============================================================================

enum TopicConfig {{

    // MARK: - Identity
    static let appName = {swift_str(t["appName"])}
    static let tagline = {swift_str(t.get("tagline", ""))}
    static let aboutText = {swift_str(t.get("aboutText", ""))}

    // MARK: - Contact / URLs
    static let supportEmail = {swift_str(t.get("supportEmail", "you@example.com"))}
    static let websiteURL = URL(string: {swift_str(t.get("websiteURL", "https://example.com"))})!
    static let privacyPolicyURL = URL(string: {swift_str(t.get("privacyURL", "https://example.com/privacy.html"))})!

    // MARK: - Categories (the tabs)
    static let categories: [TopicCategory] = [
{cats_block}
    ]

    // MARK: - Metric facet (nil hides it)
    static let metricLabel: String? = {swift_opt(t.get("metricLabel"))}
    static let metricSymbol = {swift_str(t.get("metricSymbol", "number"))}
    static let metricThresholds = [{thresholds}]

    // MARK: - Facets shown
    static let showRegionFilter = {str(t.get("showRegionFilter", True)).lower()}
    static let showDateFacet = {str(t.get("showDateFacet", True)).lower()}

    // MARK: - First-launch disclaimer (nil = none)
    static let disclaimerTitle: String? = {swift_opt(t.get("disclaimerTitle"))}
    static let disclaimerBody: String? = {swift_opt(t.get("disclaimerBody"))}

    // MARK: - Feature flags
    static let showArticleImages = {str(t.get("showArticleImages", False)).lower()}

    // MARK: - Derived (don't edit)
    static var wikimediaUserAgent: String {{
        "\\(appName.replacingOccurrences(of: " ", with: ""))/1.0 "
        + "(\\(websiteURL.absoluteString); \\(supportEmail))"
    }}

    static func category(for id: String) -> TopicCategory? {{
        categories.first {{ $0.id == id }}
    }}
}}
'''


def hex_to_components(h):
    h = h.lstrip("#")
    r, g, b = h[0:2], h[2:4], h[4:6]
    return f"0x{r.upper()}", f"0x{g.upper()}", f"0x{b.upper()}"


def write_accent(dest_root, ident, accent_hex):
    r, g, b = hex_to_components(accent_hex)
    contents = {
        "colors": [{
            "color": {"color-space": "srgb",
                      "components": {"alpha": "1.000", "blue": b, "green": g, "red": r}},
            "idiom": "universal",
        }],
        "info": {"author": "xcode", "version": 1},
    }
    path = dest_root / ident / "Resources" / "Assets.xcassets" / "AccentColor.colorset" / "Contents.json"
    path.write_text(json.dumps(contents, indent=2) + "\n")


def rename_tree(dest_root, ident, bundle_id, app_name):
    # Rename paths WikiReader -> ident (deepest first)
    for p in sorted(dest_root.rglob("*"), key=lambda p: -len(str(p))):
        if TEMPLATE_NAME in p.name:
            p.rename(p.with_name(p.name.replace(TEMPLATE_NAME, ident)))
    # Replace contents
    text_ext = {".swift", ".pbxproj", ".plist", ".json", ".xcscheme", ".md",
                ".xcworkspacedata", ".py", ".gitignore", ""}
    for dp, dirs, files in os.walk(dest_root):
        dirs[:] = [d for d in dirs if d not in EXCLUDE]
        for f in files:
            fp = os.path.join(dp, f)
            if pathlib.Path(fp).suffix.lower() not in text_ext:
                continue
            try:
                s = open(fp, encoding="utf-8").read()
            except (UnicodeDecodeError, IsADirectoryError):
                continue
            o = s
            s = s.replace(TEMPLATE_BUNDLE, bundle_id)
            # Only the CFBundleDisplayName gets the spaced app name. Doing a broad
            # "WikiReader" -> app name swap would also clobber quoted path strings
            # like "WikiReader" in the scripts/tests (they need the folder ident).
            s = s.replace(f'INFOPLIST_KEY_CFBundleDisplayName = "{TEMPLATE_NAME}"',
                          f'INFOPLIST_KEY_CFBundleDisplayName = "{app_name}"')
            s = s.replace(TEMPLATE_NAME, ident)                    # identifier everywhere else
            if s != o:
                open(fp, "w", encoding="utf-8").write(s)


def main():
    ap = argparse.ArgumentParser(description="Scaffold a new WikiReader app from topic.json.")
    ap.add_argument("topic", help="Path to topic.json")
    ap.add_argument("--out", required=True, help="Destination folder for the new app")
    args = ap.parse_args()

    topic = json.loads(pathlib.Path(args.topic).read_text())
    for key in ("appName", "bundleId", "accentHex", "categories"):
        if key not in topic:
            print(f"error: topic.json missing required key '{key}'", file=sys.stderr)
            return 2

    ident = identifier(topic["appName"])
    dest = pathlib.Path(args.out).expanduser().resolve()
    if dest.exists():
        print(f"error: destination already exists: {dest}", file=sys.stderr)
        return 2

    print(f"Scaffolding '{topic['appName']}'  (target: {ident})")
    shutil.copytree(TEMPLATE_ROOT, dest,
                    ignore=shutil.ignore_patterns(*EXCLUDE, "*.xcuserstate", "xcuserdata"))

    rename_tree(dest, ident, topic["bundleId"], topic["appName"])

    # Overwrite the generated config + accent + carry the topic.json along.
    (dest / ident / "Topic" / "TopicConfig.swift").write_text(render_topic_config(topic))
    write_accent(dest, ident, topic["accentHex"])
    (dest / "topic.json").write_text(json.dumps(topic, indent=2, ensure_ascii=False) + "\n")

    print(f"""
Done. Next:
  cd {dest}
  python3 Scripts/generate_catalog.py topic.json   # pull the catalog from Wikipedia
  python3 Scripts/validate_catalog.py              # confirm every entry resolves
  open {ident}.xcodeproj                            # build & run
""")
    return 0


if __name__ == "__main__":
    sys.exit(main())
